{% set name = "maesters-nwp" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 533042554ac8606f02ff4b8f0f094259f6e25d52ce26db71c036c6ad3b49dae5


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel

  run:
    - python >={{ python_min }}
    - curl
    - cdo
    - retrying
    - beautifulsoup4
    - pygrib
    - netCDF4
    - xarray
    - requests
    - loguru
    - toml
    - dask

test:
  requires:
    - python {{ python_min }}
  imports:
    - maesters
  commands:
    - cdo -h
    - curl -h

about:
  home: https://github.com/blizhan/Maesters-of-NWP
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package to get open NWP data in a elegant way
  dev_url: https://github.com/blizhan/Maesters-of-NWP

extra:
  recipe-maintainers:
    - blizhan
